name: build decoo-wiki
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          token: ${{ secrets.SEC_IN_PAT }}

      - name: install and build
        run: |
          yarn install
          yarn build

      - name: Deploy
        uses: hpcodecraft/action-deploy-workspace-to-repo@v2.2
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.SEC_IN_PAT }}
          SRC_FOLDER: build
          DEST_OWNER: decooio
          DEST_REPO: decoo-wiki-deploy
          DEST_BRANCH: main
          DEST_FOLDER: docs
